/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as HolidayTypesRouteImport } from './routes/holiday-types'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HolidayTypesIndexRouteImport } from './routes/holiday-types.index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as HolidayTypesSlugRouteImport } from './routes/holiday-types.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidayTypesRoute = HolidayTypesRouteImport.update({
  id: '/holiday-types',
  path: '/holiday-types',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidayTypesIndexRoute = HolidayTypesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HolidayTypesRoute,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DestinationsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const HolidayTypesSlugRoute = HolidayTypesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HolidayTypesRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/holiday-types': typeof HolidayTypesRouteWithChildren
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/holiday-types/$slug': typeof HolidayTypesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/holiday-types/': typeof HolidayTypesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/faq': typeof FaqRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/holiday-types/$slug': typeof HolidayTypesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/holiday-types': typeof HolidayTypesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/holiday-types': typeof HolidayTypesRouteWithChildren
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/holiday-types/$slug': typeof HolidayTypesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/holiday-types/': typeof HolidayTypesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/deals'
    | '/destinations'
    | '/faq'
    | '/holiday-types'
    | '/quote'
    | '/reviews'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/holiday-types/$slug'
    | '/blog/'
    | '/destinations/'
    | '/holiday-types/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/deals'
    | '/faq'
    | '/quote'
    | '/reviews'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/holiday-types/$slug'
    | '/blog'
    | '/destinations'
    | '/holiday-types'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/deals'
    | '/destinations'
    | '/faq'
    | '/holiday-types'
    | '/quote'
    | '/reviews'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/holiday-types/$slug'
    | '/blog/'
    | '/destinations/'
    | '/holiday-types/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DealsRoute: typeof DealsRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  FaqRoute: typeof FaqRoute
  HolidayTypesRoute: typeof HolidayTypesRouteWithChildren
  QuoteRoute: typeof QuoteRoute
  ReviewsRoute: typeof ReviewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holiday-types': {
      id: '/holiday-types'
      path: '/holiday-types'
      fullPath: '/holiday-types'
      preLoaderRoute: typeof HolidayTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holiday-types/': {
      id: '/holiday-types/'
      path: '/'
      fullPath: '/holiday-types/'
      preLoaderRoute: typeof HolidayTypesIndexRouteImport
      parentRoute: typeof HolidayTypesRoute
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/holiday-types/$slug': {
      id: '/holiday-types/$slug'
      path: '/$slug'
      fullPath: '/holiday-types/$slug'
      preLoaderRoute: typeof HolidayTypesSlugRouteImport
      parentRoute: typeof HolidayTypesRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface HolidayTypesRouteChildren {
  HolidayTypesSlugRoute: typeof HolidayTypesSlugRoute
  HolidayTypesIndexRoute: typeof HolidayTypesIndexRoute
}

const HolidayTypesRouteChildren: HolidayTypesRouteChildren = {
  HolidayTypesSlugRoute: HolidayTypesSlugRoute,
  HolidayTypesIndexRoute: HolidayTypesIndexRoute,
}

const HolidayTypesRouteWithChildren = HolidayTypesRoute._addFileChildren(
  HolidayTypesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DealsRoute: DealsRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  FaqRoute: FaqRoute,
  HolidayTypesRoute: HolidayTypesRouteWithChildren,
  QuoteRoute: QuoteRoute,
  ReviewsRoute: ReviewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
